FROM golang:1.3

ENV LOGSTASH_FORWARDER_REF v0.4.0
ENV _SOURCE /go/src/elasticsearch/logstash-forwarder

RUN git clone https://github.com/elasticsearch/logstash-forwarder.git "$_SOURCE" \
	&& cd "$_SOURCE" \
	&& git checkout "$LOGSTASH_FORWARDER_REF"
WORKDIR $_SOURCE

RUN go get -v -d
RUN CGO_ENABLED=0 go install -v -a -tags netgo -ldflags "-w -X main.Version '$(git describe --tags | sed s/^v//)'"

ENTRYPOINT ["logstash-forwarder"]
